recipebook/ledger/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView, RecipeCreateView, RecipeImageAddView

urlpatterns = [
    path('recipes/list/', RecipeListView.as_view(), name='recipe_list'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe'),
    path('recipe/add/', RecipeCreateView.as_view(), name='recipe_create'),
    path('recipe/<int:pk>/add_image/', RecipeImageAddView.as_view(), name='recipe_add_image'),
]

app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ledger.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/ledger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ingredient_detail', args=[self.pk])

class Recipe(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='recipes', default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('recipe', args=[self.pk])

class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=100, null=True) 
    ingredient = models.ForeignKey(
        Ingredient, 
        on_delete=models.CASCADE,
        related_name='recipe')
    recipe = models.ForeignKey(
        Recipe, 
        on_delete=models.CASCADE,
        related_name='ingredients')
    
    def __str__(self):
        return '{} of {} in {}'.format(self.ingredient.name, self.quantity, self.recipe.name)
    
class RecipeImage(models.Model):
    image = models.ImageField(upload_to='recipe_image/', null=False)
    description = models.CharField(max_length=255)
    recipe = models.ForeignKey(
        Recipe, 
        on_delete=models.CASCADE, 
        related_name='images')
    
    def get_absolute_url(self):
        return reverse('image', args=[self.pk])
    

recipebook/ledger/forms.py
from django import forms
from .models import Recipe, Ingredient, RecipeIngredient, RecipeImage

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']
    
class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']

class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['quantity', 'ingredient', 'recipe']

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = ['image','description']
        

recipebook/ledger/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from . import models
from .models import Recipe, RecipeImage
from .forms import RecipeForm, IngredientForm, RecipeIngredientForm, RecipeImageForm

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipe_list.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipe.html'
    
class RecipeCreateView(LoginRequiredMixin, CreateView):
    template_name = 'recipe_create.html'
    
    def get(self, request):
        return render(request, self.template_name, {
            'recipe_form': RecipeForm(),
            'ingredient_form': IngredientForm(),
            'recipe_ingredient_form': RecipeIngredientForm(),
        })
    
    def post(self, request, *args, **kwargs):
        print(request.POST)
        if 'recipe' in request.POST:
            print("recipe saved")
            recipe_form = RecipeForm(request.POST)
            if recipe_form.is_valid():
                recipe = recipe_form.save(commit=False)
                profile = get_object_or_404(models.Profile, user=request.user)
                recipe.author = profile
                recipe.save()
                print("POST data:", request.POST)
                recipe_ingredient_form = RecipeIngredientForm(initial={'recipe': recipe})
                ingredient_form = IngredientForm()
                return redirect('ledger:recipe_create')
            else:
                ingredient_form = IngredientForm()
                recipe_ingredient_form = RecipeIngredientForm()
        if 'ingredient' in request.POST:
            print("ingredient saved")
            ingredient_form = IngredientForm(request.POST)
            if ingredient_form.is_valid():
                ingredient_form.save()
                print("POST data:", request.POST)
                return redirect('ledger:recipe_create')
            else:
                recipe_form = RecipeForm()
                recipe_ingredient_form = RecipeIngredientForm()
        if 'recipe_ingredient' in request.POST:
            print("recipe ingredient saved")
            recipe_ingredient_form = RecipeIngredientForm(request.POST)
            if recipe_ingredient_form.is_valid():
                recipe_ingredient_form.save()
                print("POST data:", request.POST)
                return redirect('ledger:recipe_create')
            else:
                recipe_form = RecipeForm()
                ingredient_form = IngredientForm()

        return render(request, self.template_name, {
            'recipe_form': recipe_form,
            'ingredient_form': ingredient_form,
            'recipe_ingredient_form': recipe_ingredient_form,
        })
    
class RecipeImageAddView(LoginRequiredMixin, CreateView):
    model = RecipeImage
    template_name = "recipe_add_image.html"

    def get(self, request, pk):
        recipe = get_object_or_404(models.Recipe, pk=pk)
        return render(request, self.template_name, 
                      {"recipe_add_image_form": RecipeImageForm(),
                       "recipe": recipe
                       })
    
    def post(self, request, pk):
        print(request.POST)
        recipe = get_object_or_404(models.Recipe, pk=pk)
        add_image_form = RecipeImageForm(request.POST, request.FILES)
        if add_image_form.is_valid():
            image = add_image_form.save(commit=False)
            image.recipe = recipe
            image.save()
            return redirect('ledger:recipe', pk=pk)
        return render(request, self.template_name, {
            "recipe_add_image_form": add_image_form,
            "recipe": recipe
        })
    
    def get_success_url(self):
        return reverse_lazy(
            'ledger:recipe_detail',
            kwargs={'pk': self.kwargs['pk']}
        )
            
        

recipebook/ledger/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipe Book{% endblock %}</title>
    </head>
<body>
    <header>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Logout</button>
        </form>
    </header>
    <h1>Recipe Book</h1>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

recipebook/ledger/templates/recipe.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
    <h2>{{ recipe.name }}</h2>
    <p><b>By</b> {{ recipe.author }}</p>
    <p><b>Created on</b> {{ recipe.created_on }}</p>
    <p><b>Last Updated on</b> {{ recipe.updated_on }}</p>
    <h3>Ingredients:</h3>
    <ul>
        {% for ingredient in recipe.ingredients.all %}
            <li>{{ ingredient.quantity }} x {{ ingredient.ingredient.name }}</li>
        {% endfor %}
    </ul>
    <a href = "{% url 'ledger:recipe_add_image' recipe.pk %}"> Add an Image</a>
    {% if recipe.images.all %}
        {% for image in recipe.images.all %}
            <img src="{{ image.image.url }}" alt="{{ image.decription }}">
        {% endfor %}
    {% endif %}
    <footer>
        <a href = "{% url 'ledger:recipe_list' %}"> Return to Recipe List</a>
    </footer>
{% endblock%}

recipebook/ledger/templates/recipe_add_image.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Add an Image {% endblock %}
{% block content %}
    <h2>Add an Image for {{ recipe.name }}</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ recipe_add_image_form.as_p }}
        <button type="submit"> Upload image </button>
    </form>
{% endblock %}

recipebook/ledger/templates/recipe_create.html
{% extends 'base.html' %}

{% block title %} Create a New Recipe {% endblock %}
{% block content %}
    <h2> Add Recipe</h2>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ recipe_form.as_p }}
            <button type="submit" name="recipe"> Submit</button>
        </form>
    </div>

    <h2> Add Ingredient</h2>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ ingredient_form.as_p }}
            <button type="submit" name="ingredient"> Submit</button>
        </form>
    </div>


    <h2> Add Recipe Ingredient</h2>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ recipe_ingredient_form.as_p }}
            <button type="submit" name="recipe_ingredient"> Submit</button>
        </form>        
    </div>


    <p>
        <a href="{% url 'ledger:recipe_list' %}"> <button type="button"> Back to Recipes List </button> </a>
    </p>

{% endblock %}

recipebook/ledger/templates/recipe_list.html
{% extends 'base.html' %}

{% block title %}Recipe List{% endblock %}
{% block content %}
    <h2>Recipe List</h2>
    <ul>
        {% for recipe in object_list %}
            <li>
                <a href = "{% url 'ledger:recipe' recipe.pk %}">
                    {{ recipe.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <p>
        <a href = "{% url 'ledger:recipe_create' %}"> Create a New Recipe</a>
    </p>
{% endblock %}